[mypy]
python_version = 3.13
plugins = mypy_django_plugin.main


check_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_decorators = True
strict_optional = True
no_implicit_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True
show_error_codes = True
pretty = True


# 🔑 Evita que o mypy mapeie o mesmo arquivo por mais de uma raiz
explicit_package_bases = True

exclude = venv

[mypy.plugins.django-stubs]
django_settings_module = setup.settings
strict_settings = False

[mypy-*.migrations.*]
ignore_errors = True

[mypy-dotenv.*]
ignore_missing_imports = True

[mypy-faker.*]
ignore_missing_imports = True

[mypy-parameterized.*]
ignore_missing_imports = True
