[pytest]
DJANGO_SETTINGS_MODULE = setup.settings
python_files = test_*.py tests_*.py *_test.py *_tests.py

addopts =
    --doctest-modules
    --ignore=manage.py
    --strict-markers
    --tb=short
    --disable-warnings
    --cov=.
    --cov-report=term-missing
    --cov-report=html

markers =
    slow: Run tests thar are slow
    fast: Run fast tests
    functional_test: Run test that are selenium based
