# Generated by Django 5.2.8 on 2026-03-02 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('create', 'Create'),
                            ('update', 'Update'),
                            ('delete', 'Delete'),
                        ],
                        max_length=50,
                    ),
                ),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.BigIntegerField()),
                (
                    'audience',
                    models.CharField(
                        choices=[
                            ('manager', 'Manager'),
                            ('analyst', 'Analyst'),
                            ('support', 'Support'),
                        ],
                        max_length=50,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'triggered_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_triggered_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'notification',
                'indexes': [
                    models.Index(fields=['action'], name='idx_notification_action'),
                    models.Index(
                        fields=['triggered_by'], name='idx_notification_triggered_by'
                    ),
                ],
            },
        ),
    ]
