# Generated by Django 5.2.8 on 2026-03-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
