# Generated by Django 5.2.8 on 2026-03-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0002_alter_notification_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='audience',
            field=models.CharField(
                choices=[
                    ('all', 'All'),
                    ('manager', 'Manager'),
                    ('analyst', 'Analyst'),
                    ('support', 'Support'),
                ],
                max_length=50,
            ),
        ),
    ]
