# Generated by Django 5.2.8 on 2026-03-01 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('create', 'Create'),
                            ('update', 'Update'),
                            ('soft_delete', 'Soft Delete'),
                            ('hard_delete', 'Hard Delete'),
                            ('view', 'View'),
                        ],
                        max_length=50,
                    ),
                ),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'audit',
                'indexes': [
                    models.Index(
                        fields=['entity_type', 'entity_id'], name='idx_audit_entity'
                    ),
                    models.Index(
                        fields=['action', 'created_at'], name='idx_audit_action_created'
                    ),
                    models.Index(fields=['created_by'], name='idx_audit_created_by'),
                ],
            },
        ),
    ]
