# Generated by Django 5.2.8 on 2026-03-01 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='audit',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated_by',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
